### ISSUE TITLE
Are you bypassing mergebox?

### ISSUE THREAD

**Issue by theodorDiaconu** [RocketChat/meteor-streamer#23]
https://github.com/RocketChat/meteor-streamer/blob/master/packages/rocketchat-streamer/server/server.js#L290

From here I see that mergebox will still keep the last event emitted. Is this true ?

**Comment by sampaiodiego** [comment]
true, we're not bypassing mergebox. AFAIK this is not possible.

the implementation is to make the mergebox the smaller as possible.

**Comment by theodorDiaconu** [comment]
@sampaiodiego look here https://github.com/peerlibrary/meteor-control-mergebox
