### ISSUE TITLE
Horizontal Scaling

### ISSUE THREAD

**Issue by rubenpa** [RocketChat/meteor-streamer#26]
Thanks for the great package!  

I had a quick inquiry.  Does this package support horizontal scaling?  I read that the arunoda meteor streams package did not support it, and I need to implement this on more than one Galaxy container in the same app.  

If not, are there any suggested ways to implement it?

**Comment by maxnowack** [comment]
I've build a sync via mongo to support horizontal scaling in our app. It's not the best eay in my opinion, but it works.

**Comment by rubenpa** [comment]
Thanks @maxnowack.  Is there a library you used to do this?  My use of streams doesn't touch the db, so I'm not sure exactly how this would work.

**Comment by maxnowack** [comment]
I've just published the code as a npm package :)
https://github.com/maxnowack/meteor-sync-eventemitter

**Comment by rubenpa** [comment]
Wow!  Thank you so much!! Perhaps this should be integrated into this package.
