### ISSUE TITLE
How to communicate between servers

### ISSUE THREAD

**Issue by fuatsengul** [RocketChat/meteor-streamer#6]
Hi,
I liked this package but couldn't understand how to make a connection between two seperate meteor server. Currently, they are using the same database and one of them writes new data(realtime data from IoT devices) and another publishes the db to UI. So I need both server-server and server-client connection at the same time. Also, all the servers are clustered, maybe a special configuration is needed too.

Please enlighten me!
Thanks.

**Comment by rodrigok** [comment]
Hi @fuatsengul, there isn't a easy way to broadcast stream between process, you can try to follow this simple example:

```javascript
const connection = DDP.connect('localhost:3000', {_dontPrintErrors: true});

Meteor.StreamerCentral.on('broadcast', (streamName, eventName, args) => {
	connection.call('stream', streamName, eventName, args, (error, response) => {
		// Process response
	});
});

Meteor.methods({
	stream(streamName, eventName, args) {
		// Prevent call from self and client
		if (!this.connection) {
			return 'self-not-authorized';
		}

		if (!Meteor.StreamerCentral.instances[streamName]) {
			return 'stream-not-exists';
		}

		Meteor.StreamerCentral.instances[streamName]._emit(eventName, args);

		return undefined;
	}
})
```

**Comment by fuatsengul** [comment]
Thank you for quick return @rodrigok 
I's a good example, probably would work on regular meteor apps, but I think I have figure out a proper way to integrate with meteorhacks:cluster to deal with clustered server which they has different DDP endpoints.
Thanks again, I'm closing this, I will add working code when I make it work.

**Comment by rodrigok** [comment]
Awesome @fuatsengul, will be very helpful to have a guide for clusters :)

As soon as possible I will try to implement a better native solution for broadcast using another package we are using now https://github.com/Konecty/meteor-multiple-instances-status
